[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.93.2"

[context.production]
    command = "hugo --gc -b ${URL}"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = "hugo --gc --themesDir themes/stack -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
    command = "hugo --gc --themesDir themes/stack -b ${DEPLOY_PRIME_URL}"


